AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal Glue Spark Job with helper zip and CloudWatch logging

Parameters:
  ScriptBucket:
    Type: String
    Description: S3 bucket where Glue scripts are stored
  ScriptPrefix:
    Type: String
    Default: glue-scripts
    Description: Prefix/folder inside the bucket for scripts

Resources:
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: minimal-glue-job
      Role: arn:aws:iam::861276118242:role/gluerole
      Command:
        Name: glueetl
        ScriptLocation: !Sub 's3://${ScriptBucket}/job-script.py'
        PythonVersion: '3'
      DefaultArguments:
        --test: test-glue-job
        --extra-py-files: !Sub 's3://${ScriptBucket}/helpers.zip'
        --enable-continuous-cloudwatch-log: 'true'
        --enable-metrics: 'true'
        --job-bookmark-option: 'job-bookmark-disable'
      GlueVersion: '3.0'
      ExecutionProperty:
        MaxConcurrentRuns: 1
      MaxRetries: 0
      WorkerType: G.1X
      NumberOfWorkers: 2
